namespace = "functional"

[subsystem]
service_path = "functional::invoker::Invoker"
service_mem = 256
service_cpus = 256
service_grace = 60
rescaler_path = "functional::rescaler::FunctionalRescaler"
rescaler_mem = 512
rescaler_timeout = 10

[functional]
path = "functional::echo::Echo"
mem_size = 128
timeout = 3
concurrency = 1