namespace = "microbench"


[functional]
path = "microbench::MicroFunction"
mem_size = 2048
timeout = 2
concurrency = 1
caller_mem = 512


[messaging]
path = "microbench::MicroActor"
mem_size = 4096
timeout = 30
caller_mem = 512