namespace = "persistence"

[subsystem]
service_path = "persistence::LogReplica"
service_mem = 2048
service_cpus = 1024
service_grace = 60
rescaler_path = "persistence::LogRescaler"
rescaler_mem = 512
rescaler_timeout = 10

[messaging]
path = "persistence::Counter"
mem_size = 8192
timeout = 2
