namespace = "messaging"

[subsystem]
service_path = "messaging::MessagingHandler"
service_mem = 256 # Does not matter.
service_cpus = 256 # Does not matter.
service_grace = 60 # Does not matter.
rescaler_path = "messaging::MessagingRescaler"
rescaler_mem = 512
rescaler_timeout = 10

[messaging]
path = "messaging::Echo"
mem_size = 512
timeout = 5
fn_mem = 512