[package]
name = "obelisk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path="./common"}
functional = {path="./functional"}
# messaging = {path="./messaging"}
persistence = {path="./persistence"}
# microbench = {path="./microbench"}

[workspace]
members = [
    "functional",
    "common",
    # "messaging",
    "persistence",
    # "microbench",
]